const mongoose = require('mongoose');
var autoIncrement = require("mongodb-autoincrement");

var Schema = mongoose.Schema;

var BadgeSchema = new Schema({
    id: { type: Number, unique: true, required: true, autogenerated: true},
    name: { type: String, required: true },
});


// Compile model from schema
module.exports = mongoose.model('Badge', BadgeSchema );