const mongoose = require('mongoose');
var autoIncrement = require("mongodb-autoincrement");

var Schema = mongoose.Schema;

var TransactionSchema = new Schema({
    id: { type: Number, unique: true, required: true, autogenerated: true},
    date: { type: date, required: true },
    offerID: { type: Number},
    publicationID: { type: Number},
});


// Compile model from schema
module.exports = mongoose.model('Transaction', TransactionSchema );